name: Trace
description: Cryptocurrency portfolio and market explorer.

environment:
  sdk: '>=2.10.0 <3.0.0'
  
dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.5
  path_provider: ^2.0.1
  url_launcher: ^6.0.3
  http: ^0.13.3
  package_info: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0

flutter_icons:
  android: false
  ios: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/